blog/views/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from sqlalchemy.exc import IntegrityError
from werkzeug.exceptions import NotFound

from blog.models.database import db
from blog.models import User, Tag
from blog.forms.user import RegistrationForm, LoginForm

# Создаем Blueprint
auth_app = Blueprint("auth_app", __name__)

login_manager = LoginManager()  # Инициализируем объект для обработки авторизации
login_manager.login_view = "auth_app.login"  # Указываем view для авторизации


@login_manager.user_loader  # Вытаскиваем искомого пользователя (по ID);
def load_user(user_id):
    return User.query.filter_by(id=user_id).one_or_none()


@login_manager.unauthorized_handler  # Указываем обработку не авторизированной попытки доступа к защищённым view.
def unauthorized():
    return redirect(url_for("auth_app.login"))  # Выполняем редирект на страницу авторизации


# view для регистрации
# view для входа просто по юзернейму
@auth_app.route("/login/", methods=["GET", "POST"], endpoint="login")
def login():
    if current_user.is_authenticated:
        return redirect("index")

    form = LoginForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        # temp = form.username.data
        # db.create_all()
        user = User.query.filter_by(username=form.username.data).one_or_none()
        if user is None:
            return render_template("auth/login.html", form=form, error="username doesn't exist")
        if not user.validate_password(form.password.data):
            return render_template("auth/login.html", form=form, error="invalid username or password")

        login_user(user)
        return redirect(url_for("index"))

    return render_template("auth/login.html", form=form)
    # if request.method == "GET":
    #     return render_template("auth/login.html")
    #
    # username = request.form.get("username")
    # if not username:
    #     return render_template("auth/login.html", error="username not passed")
    #
    # user = User.query.filter_by(username=username).one_or_none()
    # if user is None:
    #     return render_template("auth/login.html", error=f"no user {username!r} found")
    #
    # login_user(user)
    # return redirect(url_for("index"))


# Авторизацию по юзернейму оставляем админу в виде login-as
@auth_app.route("/login-as/", methods=["GET", "POST"], endpoint="login-as")
def login_as():
    if not (current_user.is_authenticated and current_user.is_staff):
        # Пользователи без прав администратора не должны знать об этой функции
        raise NotFound


# view для вЫхода
@auth_app.route("/logout/", endpoint="logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("index"))


# view, которое требует авторизации чтобы его можно было посмотреть
@auth_app.route("/secret/")
@login_required
def secret_view():
    return "Super secret data"


# Добавляем регистрацию. Используем форму для проверки введенных данных, валидируем почту и юзернейм.
@auth_app.route("/register/", methods=["GET", "POST"], endpoint="register")
def register():
    if current_user.is_authenticated:
        return redirect("index")

    error = None
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template("auth/register.html", form=form)

        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template("auth/register.html", form=form)

        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            is_staff=False,
        )
        user.password = form.password.data
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create user!")
            error = "Could not create user!"
        else:
            current_app.logger.info("Created user %s", user)
            login_user(user)
            return redirect(url_for("index"))
    return render_template("auth/register.html", form=form, error=error)


#  Указываем объекты, которые будем импортировать
__all__ = [
    "login_manager",
    "auth_app",
]

blog/templates/base.html
<!--базовый шаблон -->
<!DOCTYPE html>
<html lang="ru">
    <head>
        <!-- Обязательные метатеги -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link  rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
          <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/fontawesome.css') }}">


          <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='ckeditor5/sample/css/sample.css') }}">

          <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/default.css') }}">
          <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='apexchart/apexcharts.css') }}">




        <title>
        {% block title %}
            Base
        {% endblock %}
        </title>
    </head>
    <body>
    <!--Для работы динамических компонентов-->
    <script  src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
    </body>
</html>

blog/templates/footer.html
<div class="footer-rg">
  <div class="container">
    <p class="text-muted ml-3">© Федеральная служба войск национальной гвардии РФ, 2022</p>
  </div>
</div>

blog/templates/header.html
<div class="row">
    <div class="col-lg-1 col-md-2 right hidden-sm hidden-xs">
        <img src="{{ url_for('static', filename='img/gerb.png') }}">
    </div>
    <div class="col-lg-2 left hidden-md hidden-sm hidden-xs">
        <p class="intop">ВОЙСКА<br>НАЦИОНАЛЬНОЙ ГВАРДИИ<br>РОССИЙСКОЙ ФЕДЕРАЦИИ</p>
    </div>
    <div class="col-lg-6 col-md-8 col-sm-12 center">
        <h1 class="title-yarus">ТЕСТОВАЯ СТРАНИЦА</h1>
        <p class="downlogo">СТРАНИЦА ДЛЯ РАБОТЫ</p>
    </div>
    <div class="col-lg-2 right hidden-md hidden-sm hidden-xs">
    <p class="intop-right">ДОГОВОРНО-ПРАВОВОЙ <br>ДЕПОРТАМЕНТ</p>
    </div>
    <div class="col-lg-1 col-md-2 left hidden-sm hidden-xs">
        <img src="{{ url_for('static', filename='img/itlogo.png') }}">
    </div>
</div>

blog/templates/index.html
<!--шаблон индекса-->
{% extends 'base.html' %}

{% block title %}
    Index Page
{% endblock %}
{% include "header.html" %}

{% block body %}
    <h1>Hello
    {% if current_user.is_authenticated %}
        {{ current_user.username }}
    {% else %}
        anon
    {% endif %}
    </h1>
{% endblock %}

blog/templates/navigation_bar.html
    <!--    панель навигации-->

    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('index') }}">Blog
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% for (endpoint, label) in [
                                ('users_app.list', 'Users'),
                                ('articles_app.list', 'Articles'),
                                ('authors_app.list', 'Authors'),
                            ] %}
                    <a href="{{ url_for(endpoint) }}"
                       class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">{{ label }}
                    </a>
                {% endfor %}
            </div>
        </div>
    <!--        добавляя информацию об авторизации в навигацию:-->
         <div class="navbar-nav ms-auto">
                {% for (endpoint, label) in [('auth_app.register', 'Register')] %}
                    <a href="{{ url_for(endpoint) }}"
                            class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">{{ label }}
                    </a>
                {% endfor %}
                 {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('auth_app.logout') }}">Logout</a>
                 {% else %}
                    <a href="{{ url_for('auth_app.login') }}"
                       class="nav-link {% if request.endpoint == 'login' -%}active{%- endif %}">
                        Login
                    </a>
                {% endif %}
        </div>
       </div>
    </nav>
        <div class="container">
            {% block body %}
                Hello base!
            {% endblock %}
        </div>